#!/bin/sh
# Hacky script for testing purposes
pkill -f cpangrep-matcher
pkill -f cpangrep-indexer

if ! pgrep redis-server; then
  (cd var; redis-server)&
  sleep .2
fi

perl bin/cpangrep-matcher&
exec perl `which starman` app.psgi
