#!/bin/sh
# Hacky script for testing purposes
pkill -f bin/cpangrep-matcher
pkill -f bin/cpangrep-index

if ! pgrep redis-server; then
  STARTED_REDIS=1
  (cd var; redis-server)&
  sleep .2
fi

echo "$(echo var/slabs/*)"

if [ "var/slabs/*" = "$(echo var/slabs/*)" ]; then
  bin/cpangrep-index
fi

perl bin/cpangrep-matcher&
trap 'if [ "$STARTED_REDIS" -gt 0 ]; then killall redis-server; wait; fi' INT
starman -R -E development app.psgi
