#!/bin/sh

kill_progs() {
  pkill -f bin/cpangrep-matcher
  pkill -f bin/cpangrep-index
}

started_redis=0
if ! pgrep redis-server; then
  started_redis=1
  (cd var; redis-server)&
  sleep .2
fi

echo "$(echo var/slabs/*)"

if [ "var/slabs/*" = "$(echo var/slabs/*)" ]; then
  bin/cpangrep-index
fi

bin/cpangrep-matcher &
trap 'if [ "$started_redis" -gt 0 ]; then killall redis-server; wait; fi; kill_progs' INT
starman -R app.psgi
